### ISSUE TITLE
Create CRUD Endpoints for HITL Lambda Function Runs

### ISSUE THREAD

**Issue by aaronxsu** [azavea/foss4g-2022-hitl-groundwork-rastervision#1]
- Add a new table for HITL lambda function runs. The following should be bare minimum. We may need to store more RV configs in this table.
```
case class HITLLambda (
  id: UUID,
  campaignId: UUID,
  projectId: UUID,
  status: Status,
  createdAt: Timestamp,
  modifiedAt: Timestamp,
  owner: String,
  version: Int
)
```
- Should enable:
    - list hitl lambda function runs by campaign and project IDs
    - get by record ID
    - post to create lambda function run record and kick off a lambda function
    - update to allow only updating the `status` and `modifiedAt`
    - delete to remove the lambda function run record

**Comment by simonkassel** [comment]
Creates a table in database with all lambda function (i.e. rv jobs) runs

**Comment by simonkassel** [comment]
points: `3`
