### ISSUE TITLE
Research semantic segmentation-specific active learning techniques

### ISSUE THREAD

**Issue by AdeelH** [azavea/foss4g-2022-hitl-groundwork-rastervision#11]
Is it enough to apply uncertainty sampling to pixels (and do some sort of aggregation) or are there other more appropriate techniques. Do a lit review to find out.

**Comment by aaronxsu** [comment]
Hey @AdeelH - what is the status of this card?

**Comment by AdeelH** [comment]
I think it's safe to close now.
