### ISSUE TITLE
Create function for prioritizing task grid cells

### ISSUE THREAD

**Issue by simonkassel** [azavea/foss4g-2022-hitl-groundwork-rastervision#12]
Inputs:
- rv predicted probability raster
- record of "human" labeled tasks
- task grid

output:
- list of task ids and certainty level
e.g.:
`[{'id': 123435, 'score': 0.8}, {'id':45678, 'score': 0.78}...]` 

will need at least example output from #4. blocking #2

**Comment by simonkassel** [comment]
I have added some sample files to simulate the output from the lambda function.

We have 

- hitl-tasks.json (s3://foss4g-hitl/hitl-tasks.json) which has the task grid for the sample project we created
- hitl-predictions.geojson (s3://foss4g-hitl/hitl-predictions.geojson) which is simply the raw geojson output from RV (clipped to our sample are for these purposes). Note that at this point there is no class field, it's just geojson geometries with no attributes:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/20233324/175990284-cb4edd12-b38f-4b46-ad90-45fa66433e66.png">

- task-priorities.json (s3://foss4g-hitl/hitl-task-priorities.json), which maps the task id to a priority score. At this point the priority score is made up but eventually it will be calculated from the probability raster that RV also outputs
```
[{'id': 'a387ce34-4261-41b0-a9fb-e11885a06b3e',
  'priority': 0.5141961877800729},
 {'id': 'cd16067e-0005-4966-be9d-092394d9662d',
  'priority': 0.5754685425905725},
 {'id': '5e6fb9fd-37b3-4f9f-bc2d-327a1b7ef637',
  'priority': 0.48375424531605177},
 {'id': '51dcf7d9-f762-428f-b337-b2d9ad8a487e',
  'priority': 0.4184376542615188},
 {'id': '68e051de-b6e1-4271-a6d1-f20efd281abc',
  'priority': 0.2778041977335458},
 {'id': '4209aa15-2e8e-4db2-9361-e9260b127399',
  'priority': 0.1826552974878332},
 {'id': '87d4eccf-f078-4ba1-80be-7ac95d488195',
  'priority': 0.6570921544966228},
 {'id': '3ae326ac-f2f8-45e7-abb6-dea5eedcd6cf',
  'priority': 0.5703887229029664},
 {'id': '7dc3fcfe-b6c8-4380-9f47-87e3c91a7bff',
  'priority': 0.6957387681930917}]
```

**Comment by aaronxsu** [comment]
### Scope of this lambda function or batch job:

#### I. Get data from GW
1. **Input**: campaign ID, project ID
2. **Output**: 
    - task grid of the project (contains geometry and task status)
    - `FeatureCollection` of all vector labels (contains geometry and class ID, with `hitl_version_id = null`, i.e. human-generated labels)
    - class definition (contains mapping between class name and class ID)
    - image/scene information (contains S3 URL of the COG image)
3. **Details**:
    - this part of the function needs a refresh token of a super user (store as env var) to get a bearer token, in order to communicate with APIs
    - all listed output are in JSON or GeoJSON format
    - all listed output can be pulled from API calls
    - the JSON shape/fields in the output will be simplified to fit the ML need
    - task cells that contain these human-generated labels are marked as "validated" and be persisted to the DB

#### II. Run RV prediction
1. **Input**:
    - task grid of the project
    - `FeatureCollection` of all vector labels
    - class definition
    - image/scene information
2. **Output**:
    - probability raster of labels
    - vector label predictions
3. **Details**:
    - TBD

#### III. Process prediction data
1. **Input**:
    - probability raster of labels
    - label predictions in vector
    - task grid
    - hitl job ID
2. **Output**:
    - vector labels in the format that GW accepts
    - task grid with updated priority scores and task status
3. **Details**:
    - mark the task cells with machine predicted labels as "labeled"
    - generate priority scores for each task cell 
    - process the machine predicted labels in a format that GW accepts, add the hitl job ID to these labels

#### IV. Persist predictions to GW
1. **Input**:
    - vector labels in the format that GW accepts with hitl job ID
    - updated task grid with new status and priority scores
2. **Output**:
    - Email and In-app notifications for user about the job status
3. **Details**:
    - Post labels to GW with hitl job ID
    - Update task grid status and priority scores 


@simonkassel @AdeelH please review the above scope and feel free to post questions in this issue. We should have some discussions in this issue and aim to have the scope finalized in this Friday's meeting.
