### ISSUE TITLE
Set up and run experiments to verify the ML part of the HITL-AL workflow

### ISSUE THREAD

**Issue by AdeelH** [azavea/foss4g-2022-hitl-groundwork-rastervision#16]
- [x] Hammer out actual training and prediction code.
- [x] See how HITL AL compares to random sampling for different %'s of data
- [x] Compare different strategies for computing priority scores.
- [x] Figure out best approach to starting model weigfhts. Start from scratch vs previous run.
- [x] Figure out good hyperparameters

**Comment by aaronxsu** [comment]
@AdeelH it looks like all tasks here are checked 🎉 , please feel free to close it when you see fit.
