### ISSUE TITLE
Create Batch Job to Make HITL predictions

### ISSUE THREAD

**Issue by aaronxsu** [azavea/foss4g-2022-hitl-groundwork-rastervision#2]
- Function env var needs to have a refresh token to communicate with RF endpoints
- Input of this function:
   - campaign and project IDs to get labels and task grid
   - label class definition
   - image S3 location
   - RV configs
- Run RV prediction using the input data
- Output of this function:
   - Call RF endpoint to post the predicted labels
   - Call RF endpoint to update task statuses
   - Call RF endpoint to update the lambda function run status
   - Send intercom message to notify success or failure

**Comment by simonkassel** [comment]
blocked by #1 and #4

**Comment by simonkassel** [comment]
Acceptance criteria: run this locally in the correct docker env pointed at staging

**Comment by aaronxsu** [comment]
More details of the function scope here: https://github.com/azavea/foss4g-2022-hitl-groundwork-rastervision/issues/12#issuecomment-1170497479

**Comment by aaronxsu** [comment]
### Scope of this lambda function or batch job:

#### I. Get data from GW
1. **Input**: campaign ID, project ID
2. **Output**: 
    - task grid of the project (contains geometry and task status)
    - `FeatureCollection` of all vector labels (contains geometry and class ID, with `hitl_version_id = null`, i.e. human-generated labels)
    - class definition (contains mapping between class name and class ID)
    - image/scene information (contains S3 URL of the COG image)
3. **Details**:
    - this part of the function needs a refresh token of a super user (store as env var) to get a bearer token, in order to communicate with APIs
    - all listed output are in JSON or GeoJSON format
    - all listed output can be pulled from API calls
    - the JSON shape/fields in the output will be simplified to fit the ML need
    - task cells that contain these human-generated labels are marked as "validated" and be persisted to the DB

#### II. Run RV prediction
1. **Input**:
    - task grid of the project
    - `FeatureCollection` of all vector labels
    - class definition
    - image/scene information
2. **Output**:
    - probability raster of labels
    - vector label predictions
3. **Details**:
    - TBD

#### III. Process prediction data
1. **Input**:
    - probability raster of labels
    - label predictions in vector
    - task grid
    - hitl job ID
2. **Output**:
    - vector labels in the format that GW accepts
    - task grid with updated priority scores and task status
3. **Details**:
    - mark the task cells with machine predicted labels as "labeled"
    - generate priority scores for each task cell 
    - process the machine predicted labels in a format that GW accepts, add the hitl job ID to these labels

#### IV. Persist predictions to GW
1. **Input**:
    - vector labels in the format that GW accepts with hitl job ID
    - updated task grid with new status and priority scores
2. **Output**:
    - Email and In-app notifications for user about the job status
3. **Details**:
    - Post labels to GW with hitl job ID
    - Update task grid status and priority scores
