### ISSUE TITLE
Add Infra in RF Terraform for Batch Job

### ISSUE THREAD

**Issue by aaronxsu** [azavea/foss4g-2022-hitl-groundwork-rastervision#3]
In the RF deployment repo, add the infrastructure necessary to run RV models and make predictions. Compute environment config should be based on further discussion with R&D.

**Comment by simonkassel** [comment]
We may need ops help (possibly to review)

**Comment by simonkassel** [comment]
Reference [this](https://github.com/azavea/foss4g-groundwork-hitl-infra) as an example
