### ISSUE TITLE
Create Training/Prediction Example Implementation Using RasterVision

### ISSUE THREAD

**Issue by aaronxsu** [azavea/foss4g-2022-hitl-groundwork-rastervision#4]
The format or data schema of input and output should be discussed as a part of this issue. 

This example should include implementation using Raster Vision to train and predict based on the input, classify results, and produce vector label output.

**Comment by simonkassel** [comment]
Output both the probability raster grid and geojson labels

**Comment by AdeelH** [comment]
Here are some existing sample RV outputs on the Freetown scene. Note that these are pretty big and slow to process on (at least my) QGIS, so we should ideally use something smaller (maybe a subset of these) for testing.

GeoJSON (243 MB):
```
s3://raster-vision-ahassan/wbtree/final/predict/freetown_validated/cf/ndvi_47/100_pct_data/resnet18-panoptic/predict/99f3d7eb403dd05cc215f8167f7f89d8746ee7ae7145131a31beda18915f141b-val-0-1-polygons.json
```

Probability raster (2.1 GB):
```
s3://raster-vision-ahassan/wbtree/final/predict/super_ensemble/freetown_se_raw_tta.tiff
```

**Comment by aaronxsu** [comment]
@AdeelH please find the sample data in the zipped directory. The following lists the structure and what each file is. They are directly from the API. The lambda function will use the same data model. Please let me know if you have questions! I am happy to hop on a call to walk you through!
```
$ tree
.
├── freetown-image-sample.json                             
├── freetown-label-class-definition-sample.json
├── freetown-labels-sample.geojson                     
└── freetown-task-grid-sample.geojson

0 directories, 4 files
```
- `freetown-image-sample.json`: this is the image info with S3 URL to COG and band info 
- `freetown-label-class-definition-sample.json`: label class definition
- `freetown-labels-sample.geojson`: labels
- `freetown-task-grid-sample.geojson`: task grid containing the above labels

[freetown-sample-20220607.zip](https://github.com/azavea/foss4g-2022-hitl-groundwork-rastervision/files/8856576/freetown-sample-20220607.zip)

cc @simonkassel

**Comment by AdeelH** [comment]
@aaronxsu, in case of multiple classes, will there separate label and label-definition files for each class? Also will these files need to be downloaded from S3 and will they always be zipped?

**Comment by AdeelH** [comment]
One more question: RV needs CRS info from the raster so that it can georeference the GeoJSON labels correctly. Is it safe to assume that the corresponding raster for the exported labels will always be at the location `results.0.dataFootprint.ingestLocation` like it is in `freetown-image-sample.json `?

Relatedly, it looks like `freetown-image-sample.json` is the raw output from a DB query. Is it possible to map this to a simpler JSON with only the most relevant fields and with more intuitive field names?

**Comment by AdeelH** [comment]
I've added a small notebook with sample code for consuming these GW exports. It's in the `rv-input` branch in this repo.

**Comment by aaronxsu** [comment]
@AdeelH thanks for looking at this. Please see my answers below:

>in case of multiple classes, will there separate label and label-definition files for each class?

Backend supports multi-class labels, but this is not a feature on frontend anymore. It is safe to assume that multi-class label is out of scope for this phase of work.

>Also will these files need to be downloaded from S3 and will they always be zipped?

Please consider these direct JSON or geojson files as input for RV. They will be provided as JSON and geojson for the RV function input. It is safe to assume: 1. no need to download, 2. no need to unzip.

>Is it safe to assume that the corresponding raster for the exported labels will always be at the location results.0.dataFootprint.ingestLocation like it is in freetown-image-sample.json ?

Yes, correct. It is safe to assume so.

>Relatedly, it looks like freetown-image-sample.json is the raw output from a DB query. Is it possible to map this to a simpler JSON with only the most relevant fields and with more intuitive field names?

This is the raw output from the API endpoint. We certainly can map this to a simpler JSON with only the relevant fields for RV  and we should align the names. This is the goal of this exercise- agree on the data schema. Please feel free to put an event on my calendar if you'd like to go through this together.

**Comment by AdeelH** [comment]
>>Relatedly, it looks like freetown-image-sample.json is the raw output from a DB query. Is it possible to map this to a simpler JSON with only the most relevant fields and with more intuitive field names?
>
>This is the raw output from the API endpoint. We certainly can map this to a simpler JSON with only the relevant fields for RV  and we should align the names. This is the goal of this exercise- agree on the data schema. Please feel free to put an event on my calendar if you'd like to go through this together.

Re: `freetown-image-sample.json`, I have reconsidered this request. I think we should leave this as it is, since it is not very important and I don't want to make any assumptions that we might need to revisit when we try to expand this work in the future.

>in case of multiple classes, will there separate label and label-definition files for each class?

We discussed in the last check-in that in case of multiple classes, `freetown-label-class-definition-sample.json` would contain definitions for all of them. Can you provide a sample file for that case? It can just be dummy data.

**Comment by aaronxsu** [comment]
>Re: freetown-image-sample.json, I have reconsidered this request. I think we should leave this as it is, since it is not very important and I don't want to make any assumptions that we might need to revisit when we try to expand this work in the future.

Sounds good.

>We discussed in the last check-in that in case of multiple classes, freetown-label-class-definition-sample.json would contain definitions for all of them. Can you provide a sample file for that case? It can just be dummy data.

Sure. Here you go. Please note that the added label class `Road` does not exist in the real project and thus no matching labels of this class in the sample label geojson. The shape of this json file also changed from one object to two objects in an array. Let me know if you have questions.

```json
[
    {
        "id": "f93963bd-b829-4ec7-a6d7-78c39b388c70",
        "name": "Tree Canopy",
        "annotationLabelClassGroupId": "bbd44df9-bd44-414e-a010-584c898f22e9",
        "colorHexCode": "#ffff55",
        "default": null,
        "determinant": null,
        "index": 0,
        "geometryType": null,
        "description": null,
        "isActive": true
    },
    {
        "id": "5d2278fe-af30-473a-b35f-72510e1df828",
        "name": "Road",
        "annotationLabelClassGroupId": "bbd44df9-bd44-414e-a010-584c898f22e9",
        "colorHexCode": "#5555ff",
        "default": null,
        "determinant": null,
        "index": 1,
        "geometryType": null,
        "description": null,
        "isActive": true
    }
]
```


@AdeelH please see the above.

**Comment by AdeelH** [comment]
Thanks!

>The shape of this json file also changed from one object to two objects in an array. Let me know if you have questions.

Having it always be an array for consistency would be nice, if that's easy to do. Otherwise, I will just need to add a check on the RV side.

**Comment by aaronxsu** [comment]
@AdeelH deal- we will keep the array data structure no matter the number of classes.
