### ISSUE TITLE
Update Annotation Label Table and Endpoints

### ISSUE THREAD

**Issue by aaronxsu** [azavea/foss4g-2022-hitl-groundwork-rastervision#5]
- Include a nullable field `version_id: UUID`, default should be `null`
- all human-generated labels will have `null` in this field
- all machine-generated labels will have corresponding value from `HITLLambda.id`, which corresponds to a version of the lambda function run. see more here: https://github.com/azavea/foss4g-2022-hitl-groundwork-rastervision/issues/1
- by default, existing endpoints for labels only return those who have `null` in this field, i.e. only return human-generated labels by default

**Comment by simonkassel** [comment]
blocked by #1
